version: "3"

services:
    nginx:
        image: nginx:alpine
        networks:
            - default
        volumes:
            - ./example_nginx:/etc/nginx/conf.d/default.conf
        ports:
            - 8080:80
        security_opt:
            - no-new-privileges:true
        restart: always

    hermes1:
        image: srgmc/hermes
        depends_on:
            - mariadb
            - nginx
        networks:
            - default
        env_file:
            - ./hermes.env
        volumes:
            - ./web/assets/places:/usr/src/app/web/assets/places:ro
        security_opt:
            - no-new-privileges:true
        restart: always

    hermes2:
        image: srgmc/hermes
        depends_on:
            - mariadb
            - nginx
        networks:
            - default
        env_file:
            - ./hermes.env
        volumes:
            - ./web/assets/places:/usr/src/app/web/assets/places:ro
        security_opt:
            - no-new-privileges:true
        restart: always

    mariadb:
        image: yobasystems/alpine-mariadb
        networks:
            - default
        env_file: ./mariadb.env
        volumes:
            - ./volumes/mariadb:/var/lib/mysql
        ports:
            - 3306:3306
        security_opt:
            - no-new-privileges:true
        restart: always
